#!/bin/bash

# Linux makeself installer
# NOTE: This is NOT a script intended to be run as a part of the linux build or configuration process!
# It is meant to be bundled within makeself to install the binaries to the correct directories.

install_OpenGLCheckWithQt () {
  # Prep stage

  # Check for file
  if [ -f ~/OpenGLCheckWithQt ]
  then
    echo "Fatal: ~/OpenGLCheckWithQt exists and is a file, not a directory"
    echo "To install, please ensure this file is renamed or moved"
    exit 1
  fi

  # Check for directory
  if [ -d ~/OpenGLCheckWithQt ]
  then
    echo "~/OpenGLCheckWithQt exists. Proceeding..."
  else
    echo "Creating ~/OpenGLCheckWithQt/..."
    mkdir ~/OpenGLCheckWithQt/
  fi

  # Version number. 'version' file should be provided by OpenGLCheckWithQt-pkg
  ver=`cat version`

  # Check version dir/file
  if [ -f ~/OpenGLCheckWithQt/${ver} ]
  then
    echo "Fatal: ~/OpenGLCheckWithQt/${ver} exists and is a file, not a directory"
    echo "To install, please ensure this file is renamed or moved"
    exit 1
  fi

  # Check for directory
  if [ -d ~/OpenGLCheckWithQt/${ver} ]
  then
    echo "~/OpenGLCheckWithQt/${ver} exists. Proceeding..."
  else
    echo "Creating ~/OpenGLCheckWithQt/${ver}/..."
    mkdir ~/OpenGLCheckWithQt/${ver}/
  fi


  # Check disk space
  echo "Checking disk space..."

  # Total free disk space is gotten with df . and we want the "availible" column. 
  # This is in kb so we need to convert to b as well
  # The middle part gets df, gets the last line of output, and gets the 4th column
  # the rest of it gets the result of that in bytes
  freedisk=`echo "$(df . | tail -n -1 | awk '{print $3}') * 1024" | bc -l`

  # Used space is gotten by analyzing the OpenGLCheckWithQt.bin file with ls -l
  useddisk=`ls -l OpenGLCheckWithQt.bin | awk '{print $5}'`

  if [ ${useddisk} -gt ${freedisk} ]
  then
    echo "Not enough free space on disk for operation. Aborting installation."
    exit 1
  fi

  # Check for FUSE
  echo "Checking for FUSE..."

  fusefail=0

  # Redirect fusermount output          
  fusermount -V 2> /dev/null

  if [ $? -ne 0 ]
  then
    fusefail=1
    echo "Warning: FUSE is not installed. See https://github.com/CBICA/OpenGLCheckWithQt/wiki/GNU-Linux-Installer-Troubleshooting#dlopen-error-loading-libfuseso2-fuse-not-installed for further information. The AppImage will continue installation as normal."
  fi

  # Move file but preserve pid
  mv ./OpenGLCheckWithQt.bin ~/OpenGLCheckWithQt/${ver}/OpenGLCheckWithQt-${ver}.bin 2>/dev/null &
  pid=$!
    
  # The latest in bash spinner technology from npm
  spin='-\|/'

  # Show a spinner until the file is done moving
  i=0
  while kill -0 $pid 2>/dev/null
  do
    i=$(( (i+1) %4 ))
    printf "\rInstalling... ${spin:$i:1}"
    sleep .1
  done
  printf "\n"

  # Last case
  chmod +x ~/OpenGLCheckWithQt/${ver}/OpenGLCheckWithQt-${ver}.bin
  if [ $? -ne 0 ]; then
    echo "WARNING: It appears as if something is wrong with your installation. Please make sure there is enough room on your disk, and that OpenGLCheckWithQt-${ver}.bin is present under ~/OpenGLCheckWithQt"
    exit 1
  fi

  # Creating a symbolic link
  echo "Creating symbolic link 'OpenGLCheckWithQt'"
  cd ~/OpenGLCheckWithQt/${ver}/
  ln -s ./OpenGLCheckWithQt-${ver}.bin OpenGLCheckWithQt

  # Display any warnings at the end
  if [ ${fusefail} -eq 1 ]
  then
    echo "WARNING: You may have issues running the AppImage since FUSE was not detected on your filesystem; please extract the installation files using the \"~/OpenGLCheckWithQt/${ver}/OpenGLCheckWithQt --appimage-extract\" option"
  fi

  echo "Done."
  echo "To run OpenGLCheckWithQt, enter the command \"~/OpenGLCheckWithQt/${ver}/OpenGLCheckWithQt\" in your console."
  
}

# Print license with a reader
cat ./Linux-Combined.txt | more

echo ""
for i in {1..3}
do
  read -p "I accept the terms of the licenses above [Y/N] " choice
  case "$choice" in 
    [yY][eE][sS]|[yY]) install_OpenGLCheckWithQt ; break  ;;
    [nN][oO]|[nN]) echo "Goodbye" ; exit 0 ;;
    * ) echo "Invalid";;
  esac
done